In [ ]:
from src.models.components.superpoint import SuperPoint
from linetr.line_detector import LSD
from linetr.line_process import preprocess, line_tokenizer
from linetr_utils.util_lines import find_line_matches, calculate_line_overlaps, conv_fixed_size
import torch
import tqdm

import os
import os.path as osp
import argparse
from datetime import date
import json
import random
import time
from pathlib import Path
import numpy as np
import numpy.linalg as LA
import torch.linalg
from tqdm import tqdm
import matplotlib as mpl
import matplotlib.pyplot as plt
import cv2
import csv

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader


import pandas as pd
import glm

In [ ]:
conf = {
    "data": {
        "name": "gcl_synth",
        "image_path": "./assets/dataset/raw_images",
        "output_path": "./assets/dataset/dataset_h5",
        "image_type": "*.jpg",
        "resize": (640, 480),
        "visualize": True,
        "n_iters": 1,
        "choose_worker": 0,
        "nWorkers": 1
    },
    "augmentation": {
        "num": 1,
        "photometric": {
            "enable": True,
            "primitives": [
                "random_brightness", "random_contrast", "additive_speckle_noise",
                "additive_gaussian_noise", "additive_shade", "motion_blur"
            ],
            "params": {
                "random_brightness": {"max_abs_change": 50},
                "random_contrast": {"strength_range": [0.3, 1.5]},
                "additive_gaussian_noise": {"stddev_range": [0, 10]},
                "additive_speckle_noise": {"prob_range": [0, 0.0035]},
                "additive_shade": {
                    "transparency_range": [-0.5, 0.5],
                    "kernel_size_range": [100, 150]
                },
                "motion_blur": {"max_kernel_size": 3}
            }
        },
        "homographic": {
            "enable": True,
            "params": {
                "perspective": True,
                "scaling": True,
                "translation": True,
                "rotation": True,
                "patch_ratio": 0.85,
                "perspective_amplitude_x": 0.2,
                "perspective_amplitude_y": 0.2,
                "scaling_amplitude": 0.2,
                "max_angle": 1.0472,
                "allow_artifacts": True
            },
            "valid_border_margin": 3
        }
    },
    "feature": {
        "linetr": {
            "min_length": 16,
            "token_distance": 8,
            "max_tokens": 21,
            "remove_borders": 1,
            "max_sublines": 250,
            "thred_reprojected": 3,
            "thred_angdiff": 2,
            "min_overlap_ratio": 0.3
        },
        "superpoint": {
            "nms_radius": 4,
            "keypoint_threshold": 0.005,
            "remove_borders": 4,
            "max_keypoints": 256
        }
    }
}


In [ ]:
device = torch.device('cuda')
model = SuperPoint(conf['feature']['superpoint']).to(device).eval()
linedetector = LSD(conf['feature']['linetr'])

In [ ]:
path = "/home/kmuvcl/source/oldCuTi/CuTi/matterport/mp3d_planercnn_json/cached_set_moon_val_vp.json"
root = "/home/kmuvcl/source/oldCuTi/CuTi/matterport/"

In [ ]:
with open(path) as file:
    split = json.load(file)

In [ ]:
len(split['data'])

In [ ]:
split['data']['0'].keys()

In [ ]:
for i in tqdm(range(len(split['data']))):
    del split['data'][str(i)]['gt_corrs']
    del split['data'][str(i)]['0']['annotations']
    del split['data'][str(i)]['1']['annotations']

In [ ]:
images_list = []
lines_list = []
vps_list = []
poses_list = []
intrinsics_list = []

original_basepath = "/Pool1/users/jinlinyi/dataset/mp3d_rpnet_v4_sep20"
data_path = "/home/kmuvcl/source/oldCuTi/CuTi/matterport"

resize = (640,480)

In [ ]:
def read_data(path, device, resize):
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    
    if resize[0] != -1:
        image = cv2.resize(image.astype('float32'), (resize[0], resize[1]))
        gray = cv2.resize(gray.astype('uint8'), (resize[0], resize[1]))
    gray_torch = torch.from_numpy(gray/255.).float()[None, None].to(device)
    
    return image, gray, gray_torch

def read_line_file(filename: str, min_line_length=10):
        segs = []  # line segments

        with open(filename, "r") as csvfile:
            csvreader = csv.reader(csvfile)
            for row in csvreader:
                segs.append([float(row[0]), float(row[1]), float(row[2]), float(row[3])])
        segs = np.array(segs, dtype=np.float32)
        lengths = LA.norm(segs[:, 2:] - segs[:, :2], axis=1)
        segs = segs[lengths > min_line_length]
        return segs
    

In [ ]:
klines_dict = {}

In [ ]:
split['data'].values()

In [ ]:
for i, data in enumerate(tqdm(split["data"].values())):
    vps = []
    images_list = []
    
    for img_idx in ["0", "1"]:
        img_path = data[img_idx]["file_name"].replace(original_basepath, data_path)
        images_list.append(img_path)
    images = []
    grays = []
    for j in range(2):
        images.append(cv2.imread(images_list[j], cv2.IMREAD_COLOR))
        
    images[0] = cv2.resize(images[0].astype('float32'), (480,640))
    images[1] = cv2.resize(images[1].astype('float32'), (480,640))
    grays.append(cv2.cvtColor(images[0], cv2.COLOR_RGB2GRAY))
    grays.append(cv2.cvtColor(images[1], cv2.COLOR_RGB2GRAY))
    
    grays[0] = cv2.resize(grays[0].astype('uint8'), (resize[0], resize[1]))
    grays[1] = cv2.resize(grays[1].astype('uint8'), (resize[0], resize[1]))
    
    image0_torch = torch.from_numpy(grays[0]/255.).float()[None, None].to(device)
    image1_torch = torch.from_numpy(grays[1]/255.).float()[None, None].to(device)
    
    height, width = image_shape = grays[0].shape
    
    with torch.no_grad():
        pred0 = model({'image': image0_torch})
        pred1 = model({'image': image1_torch})
        
    valid_mask0 = np.ones_like(grays[0])
    valid_mask1 = np.ones_like(grays[1])  
    
    klns0_cv = linedetector.detect(grays[0])
    klns1_cv = linedetector.detect(grays[1])
    
    try:
        klines0 = preprocess(klns0_cv, image_shape, pred0, mask=valid_mask0, conf=conf['feature']['linetr'])   ## TODO: torch vs. np. 잘 정리하기, tokenizer 다시 정리
        klines1 = preprocess(klns1_cv, image_shape, pred1, mask=valid_mask1, conf=conf['feature']['linetr'])
    except:
        print("line preprocess break")
        break
    klines0 = conv_fixed_size(klines0, conf, func_token=line_tokenizer, pred_sp=pred0)
    klines1 = conv_fixed_size(klines1, conf, func_token=line_tokenizer, pred_sp=pred1)
    
    klns0 = klines0['sublines'].reshape(-1, 2, 2).cpu().numpy()
    klns1 = klines1['sublines'].reshape(-1, 2, 2).cpu().numpy()
    
    keys_l = ['klines', 'sublines', 'angle_sublines','pnt_sublines', 'desc_sublines', \
            'score_sublines', 'resp_sublines', 'mask_sublines', 'num_klns', 'mat_klines2sublines', 'num_slns']
        # klines, resp, angle, pnt, desc, score, mask
    klines0 = {k:v[0] for k,v in klines0.items() if k in keys_l}
    klines1 = {k:v[0] for k,v in klines1.items() if k in keys_l}

    data['0']['klines'] = klines0
    data['1']['klines'] = klines1

    if i ==7:
        break




In [ ]:
klines_dict.keys()

In [ ]:
split['data']['0']['1']['klines']

In [ ]:
with open('cached_set_sp_moon_val_vp.json', 'w') as f : 
	json.dump(split, f, indent=4)

In [ ]:
len(klns0_cv)

In [ ]:
klines0.keys()

In [ ]:
klines0['num_slns0']

In [12]:
import h5py
import torch
import numpy as np
import math

In [44]:
def load_h5py_to_dict(file_path):
    with h5py.File(file_path, 'r') as f:
        return {key: torch.tensor(f[key][:]) for key in f.keys()}

In [70]:
dict = load_h5py_to_dict('/home/kmuvcl/source/oldCuTi/CuTi/matterport/rgb/2t7WUuJeko7/0_2_11_sp_line.h5py')

In [71]:
dict.keys()

dict_keys(['angle_sublines', 'angles', 'desc_sublines', 'klines', 'length_klines', 'mask_sublines', 'mat_klines2sublines', 'num_klns', 'num_slns', 'pnt_sublines', 'resp_sublines', 'score_sublines', 'sublines'])

In [72]:
dict['sublines']

tensor([[[[530.3347, 348.6603],
          [545.9462, 189.4237]],

         [[545.9462, 189.4237],
          [550.6509, 141.4364]],

         [[531.8973, 339.5035],
          [547.9760, 180.3134]],

         [[547.9760, 180.3134],
          [551.9709, 140.7609]],

         [[557.0982, 228.8450],
          [574.9119,  69.8398]],

         [[574.9119,  69.8398],
          [579.2292,  31.3037]],

         [[329.4134, 238.1257],
          [332.2184,  75.6094]],

         [[568.2054, 183.9740],
          [585.3932,  33.9382]],

         [[329.1623, 233.7546],
          [330.7957,  86.2450]],

         [[368.7011, 236.5312],
          [513.7408, 233.3337]],

         [[335.7190, 228.7852],
          [338.2641,  86.2860]],

         [[558.3882, 223.1540],
          [573.1456,  89.3773]],

         [[ 89.2550, 346.2133],
          [ 98.7361, 476.6145]],

         [[581.5742, 205.5860],
          [597.7986,  80.5826]],

         [[363.5614, 231.3422],
          [368.3460, 111.4334]],

         [

In [73]:
dict['sublines']

tensor([[[[530.3347, 348.6603],
          [545.9462, 189.4237]],

         [[545.9462, 189.4237],
          [550.6509, 141.4364]],

         [[531.8973, 339.5035],
          [547.9760, 180.3134]],

         [[547.9760, 180.3134],
          [551.9709, 140.7609]],

         [[557.0982, 228.8450],
          [574.9119,  69.8398]],

         [[574.9119,  69.8398],
          [579.2292,  31.3037]],

         [[329.4134, 238.1257],
          [332.2184,  75.6094]],

         [[568.2054, 183.9740],
          [585.3932,  33.9382]],

         [[329.1623, 233.7546],
          [330.7957,  86.2450]],

         [[368.7011, 236.5312],
          [513.7408, 233.3337]],

         [[335.7190, 228.7852],
          [338.2641,  86.2860]],

         [[558.3882, 223.1540],
          [573.1456,  89.3773]],

         [[ 89.2550, 346.2133],
          [ 98.7361, 476.6145]],

         [[581.5742, 205.5860],
          [597.7986,  80.5826]],

         [[363.5614, 231.3422],
          [368.3460, 111.4334]],

         [

In [84]:
dict['klines'][0,247]

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)

In [63]:
sublines = dict['sublines'][0]

In [51]:
dict['desc_sublines'].shape

torch.Size([1, 250, 21, 256])

In [52]:
def normalize_safe_np(v, axis=-1, eps=1e-6):
    de = LA.norm(v, axis=axis, keepdims=True)
    de = np.maximum(de, eps)
    return v / de

def segs2lines_np(segs):
    ones = np.ones(len(segs))
    ones = np.expand_dims(ones, axis=-1)
    p1 = np.concatenate([segs[:, :2], ones], axis=-1)
    p2 = np.concatenate([segs[:, 2:], ones], axis=-1)
    lines = np.cross(p1, p2)
    return normalize_safe_np(lines)

def normalize_segs(self, lines, pp, rho=517.97):
    pp = np.array([pp[0], pp[1], pp[0], pp[1]], dtype=np.float32)
    return (lines - pp)/rho

def sample_segs_np(segs, num_sample):
    num_segs = len(segs)
    sampled_segs = np.zeros([num_sample, 4], dtype=np.float32)
    mask = np.zeros([num_sample, 1], dtype=np.float32)
    if num_sample > num_segs:
        sampled_segs[:num_segs] = segs
        mask[:num_segs] = np.ones([num_segs, 1], dtype=np.float32)
    else:
        lengths = LA.norm(segs[:, 2:] - segs[:, :2], axis=-1)
        prob = lengths / np.sum(lengths)
        idxs = np.random.choice(segs.shape[0], num_sample, replace=True, p=prob)
        sampled_segs = segs[idxs]
        mask = np.ones([num_sample, 1], dtype=np.float32)
    return sampled_segs, mask

def coordinate_yup(segs, org_h):
    H = np.array([0, org_h, 0, org_h])
    segs[:, 1] = -segs[:, 1]
    segs[:, 3] = -segs[:, 3]
    return (H + segs)

def get_line_dist(line):
    sp = line[0]
    ep = line[1]
    return np.sqrt(np.sum((ep-sp)**2))

def point_on_line(line, dist_px):
    assert dist_px >= 0, 'distance should be positive!'
    assert get_line_dist(line) >= dist_px, 'distance should be smaller than line length!'

    sp,ep = line
    vec = ep - sp
    if vec[0] != 0:
        m = vec[1]/vec[0]
        x = np.sqrt(dist_px**2/(1+m**2))
        y = m*x
    else:
        x = 0
        y = dist_px if ep[1]-sp[1] > 0 else -dist_px

    return (x,y)+sp

def sample_descriptors(keypoints, descriptors, s: int = 8):
    """ Interpolate descriptors at keypoint locations """
    b, c, h, w = descriptors.shape
    keypoints = keypoints - s / 2 + 0.5
    keypoints /= torch.tensor([(w*s - s/2 - 0.5), (h*s - s/2 - 0.5)],
                              ).to(keypoints)[None]
    keypoints = keypoints*2 - 1  # normalize to (-1, 1)
    args = {'align_corners': True} if int(torch.__version__[2]) > 2 else {}
    descriptors = torch.nn.functional.grid_sample(
        descriptors, keypoints.view(b, 1, -1, 2), mode='bilinear', **args)
    descriptors = torch.nn.functional.normalize(
        descriptors.reshape(b, c, -1), p=2, dim=1)
    return descriptors


In [53]:
sublines.shape

torch.Size([250, 2, 2])

In [54]:
sublines 

tensor([[[437.2130, 388.4448],
         [444.6743, 228.6189]],

        [[444.6743, 228.6189],
         [452.5088,  60.8017]],

        [[452.5088,  60.8017],
         [455.2964,   1.0888]],

        [[101.4048,  66.5801],
         [112.2790, 226.2101]],

        [[112.2790, 226.2101],
         [119.9744, 339.1775]],

        [[116.9662,  64.5575],
         [129.0544, 224.1002]],

        [[129.0544, 224.1002],
         [136.4720, 322.0002]],

        [[436.9378, 383.0066],
         [444.7004, 223.1950]],

        [[444.7004, 223.1950],
         [449.3849, 126.7541]],

        [[117.1098,  66.3729],
         [129.0668, 225.9255]],

        [[129.0668, 225.9255],
         [136.0245, 318.7669]],

        [[410.7136, 348.8024],
         [414.9847, 188.7162]],

        [[449.3232, 406.2552],
         [450.7181, 251.2452]],

        [[409.4229, 395.6263],
         [413.3465, 254.3464]],

        [[337.5530,  23.8864],
         [342.6288, 161.4758]],

        [[137.4933,  66.0177],
         

In [55]:
sublines = sublines.reshape(250,-1).numpy()

In [56]:
sublines

array([[437.21295166, 388.44482422, 444.67434692, 228.61889648],
       [444.67434692, 228.61889648, 452.50878906,  60.80167007],
       [452.50878906,  60.80167007, 455.29644775,   1.08877325],
       [101.40480042,  66.58006287, 112.27898407, 226.21011353],
       [112.27898407, 226.21011353, 119.97444916, 339.17749023],
       [116.96620178,  64.55751038, 129.05438232, 224.10021973],
       [129.05438232, 224.10021973, 136.47203064, 322.00024414],
       [436.93777466, 383.00662231, 444.70040894, 223.19503784],
       [444.70040894, 223.19503784, 449.38491821, 126.75405121],
       [117.10980225,  66.37291718, 129.06684875, 225.92550659],
       [129.06684875, 225.92550659, 136.02449036, 318.76690674],
       [410.71356201, 348.80239868, 414.98474121, 188.71624756],
       [449.32318115, 406.25515747, 450.71813965, 251.24520874],
       [409.42285156, 395.62634277, 413.34649658, 254.34643555],
       [337.55297852,  23.88638878, 342.62884521, 161.47581482],
       [137.49328613,  66

In [57]:
sublines = coordinate_yup(sublines,480)

In [58]:
sublines

array([[437.21295166,  91.55517578, 444.67434692, 251.38110352],
       [444.67434692, 251.38110352, 452.50878906, 419.19832993],
       [452.50878906, 419.19832993, 455.29644775, 478.91122675],
       [101.40480042, 413.41993713, 112.27898407, 253.78988647],
       [112.27898407, 253.78988647, 119.97444916, 140.82250977],
       [116.96620178, 415.44248962, 129.05438232, 255.89978027],
       [129.05438232, 255.89978027, 136.47203064, 157.99975586],
       [436.93777466,  96.99337769, 444.70040894, 256.80496216],
       [444.70040894, 256.80496216, 449.38491821, 353.24594879],
       [117.10980225, 413.62708282, 129.06684875, 254.07449341],
       [129.06684875, 254.07449341, 136.02449036, 161.23309326],
       [410.71356201, 131.19760132, 414.98474121, 291.28375244],
       [449.32318115,  73.74484253, 450.71813965, 228.75479126],
       [409.42285156,  84.37365723, 413.34649658, 225.65356445],
       [337.55297852, 456.11361122, 342.62884521, 318.52418518],
       [137.49328613, 413

In [40]:
tokens = []
token_distance = 8
width = 640
height = 480
max_tokens = 21
slines_all, num_slines_all = [], []
tokens_all, masks_all = [], []
response_all, angle_all = [], []

In [41]:
kline = dict['klines']
klength = dict['length_klines']

In [ ]:
kline[0][0]

In [ ]:
num_tokens = int(math.ceil(klength[0][0] / 8))

In [ ]:
num_tokens

In [ ]:
for i, (kline, klength) in enumerate(zip(dict['klines'][0].numpy(), dict['length_klines'][0].numpy())):
    print(kline)
    tokens = []
    num_tokens = int(math.ceil(klength / token_distance))
    print(num_tokens)
    for i_token in range(num_tokens-1):
        dist = i_token * token_distance
        token = point_on_line(kline, dist)
        tokens.append(token)
    token = kline[1]
    token[0]=token[0].clip(max=width-0.6)
    token[1]=token[1].clip(max=height-0.6)
    tokens.append(token)
    sp,ep = kline
    num_sublines = int(math.ceil(num_tokens / max_tokens))
    sublines = np.zeros((num_sublines,2,2))
    sublines[0,0] = sp
    sublines[-1,1] = ep
    for i_sline in range(num_sublines-1):
        mid_token = tokens[(i_sline+1)*max_tokens-1]
        sublines[i_sline, 1] = mid_token
        sublines[i_sline+1, 0] = mid_token
    slines_all.extend(sublines)
    num_slines_all.append(num_sublines)

    # line tokens & masks for sublines
    tokens_sline = np.zeros((num_sublines,max_tokens,2))
    masks_sline = np.zeros((num_sublines,max_tokens+1,1))
    masks_sline[:,0] = 1

    for i_sline in range(num_sublines):
        i_start = i_sline*max_tokens
        i_end = i_start + max_tokens
        tmp_tokens = np.asarray(tokens[i_start:i_end])
        tokens_sline[i_sline,:len(tmp_tokens)] = tmp_tokens
        masks_sline[i_sline,1:len(tmp_tokens)+1] = 1
    tokens_all.extend(tokens_sline)
    masks_all.extend(masks_sline)

    resp_sline = np.zeros((num_sublines,1))
    ang_sline = np.zeros((num_sublines,2))
    max_length = token_distance * max_tokens
    for i_sline in range(num_sublines):
        resp_sline[i_sline] = get_line_dist(sublines[i_sline]) / max_length
        ang_sline[i_sline] = dict['angles'][0][i]
    response_all.extend(resp_sline)
    angle_all.extend(ang_sline)
    
    device = 'cpu'
    # device = 'cpu'
    slines = torch.from_numpy(np.vstack(slines_all).reshape(-1,2,2)).float().to(device)
    tokens = torch.from_numpy(np.vstack(tokens_all).reshape(-1,max_tokens,2)).float().to(device)
    masks = torch.from_numpy(np.vstack(masks_all).reshape(-1,max_tokens+1,1)).float().to(device)
    responses = torch.from_numpy(np.vstack(response_all).reshape(-1,1)).float().to(device)
    angles = torch.from_numpy(np.vstack(angle_all).reshape(-1,2)).float().to(device)
    
    # adjacency matrix (mat_keylines2sublines)
    klines2slines = torch.zeros((len(dict['klines'][0]), len(slines))).to(device)
    st_idx = 0
    for i, num_sline in enumerate(num_slines_all):
        klines2slines[i,st_idx:st_idx+num_sline] = 1/num_sline
        st_idx += num_sline

    # descriptors & scores for line tokens
    dense_descriptor = dict['dense_descriptor'][0]
    descriptors = sample_descriptors(tokens[None], dense_descriptor, 8)[0].reshape(256,tokens.shape[0],tokens.shape[1])
    descriptors = descriptors.permute(1,2,0)

    dense_score = dict['dense_score'].transpose(1,2)
    pos_score = [torch.round(tokens).long().reshape(-1,2)]
    pos_score[0][:,0] = pos_score[0][:,0].clip(max=dense_score.shape[1]-1)
    pos_score[0][:,1] = pos_score[0][:,1].clip(max=dense_score.shape[2]-1)
    scores = [s[tuple(k.t())] for s, k in zip(dense_score, pos_score)]
    scores = scores[0].reshape(len(slines), max_tokens, 1)
    break

In [ ]:
slines[None]

In [1]:
import torch

/home/kmuvcl/anaconda3/envs/cuti/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
vp = torch.tensor([[ 8.8663e-01, -8.8244e-02,  4.5397e-01],
         [ 0.0000e+00,  9.8163e-01,  1.9081e-01],
         [-4.6247e-01, -1.6918e-01,  8.7034e-01]]

In [9]:
vp = vp.transpose(-2,-1)

In [12]:
vp

tensor([[ 0.8866,  0.0000, -0.4625],
        [-0.0882,  0.9816, -0.1692],
        [ 0.4540,  0.1908,  0.8703]])

In [13]:
vp[0]

tensor([ 0.8866,  0.0000, -0.4625])

In [14]:
torch.dot(vp[0],vp[1])

tensor(9.0024e-07)