In [2]:
import os
import json
import math
import random
import glob
import numpy as np
import torch
# from scipy import io
# import skimage.io
# import numpy.linalg as LA
# import matplotlib.pyplot as plt
# import skimage.transform
# from torch.utils.data import Dataset
# from torch.utils.data.dataloader import default_collate
# import scipy.spatial.distance as scipy_spatial_dist
# from vpd.config import C
# from vpd.models.sphere.sphere_utils import gold_spiral_sampling_patch

In [4]:
rootdir = "/home/kmuvcl/dataset/data/scannet-vp"
split = "train"
dirs = np.genfromtxt(f"{rootdir}/scannetv2_{split}.txt", dtype=str)

In [6]:
len(dirs)

1201

In [7]:
filelist = sum([sorted(glob.glob(f"{rootdir}/{d}/*.png")) for d in dirs], [])

In [9]:
len(dirs)
len(filelist)

189916

In [10]:
if split == "train":
    num_train = int(len(filelist) * C.io.percentage)
    self.filelist = filelist[0 : num_train]
    self.size = len(self.filelist)

NameError: name 'C' is not defined

In [18]:
with np.load(filelist[0].replace("color.png", "vanish.npz")) as npz:
    print(npz['x'])
    vpts = np.array([npz[d] for d in ["x", "y", "z"]])

[-0.99024556  0.11863917  0.07306044]


In [14]:
vpts

array([[-0.99024556,  0.11863917,  0.07306044],
       [ 0.01114918, -0.45520902,  0.89031495],
       [ 0.13888343,  0.88244528,  0.44944641]])

In [15]:
vpts[0]

array([-0.99024556,  0.11863917,  0.07306044])